Crm/account/urls.py
from django.contrib.auth import views
from django.urls import path


app_name = "account"
urlpatterns = [
  path("login/", views.LoginView.as_view(), name="login"),
  path("logout/", views.LogoutView.as_view(), name="logout"),
  # path("password_change/", views.PasswordChangeView.as_view(), name="password_change"),
  # path("password_change/done/", views.PasswordChangeDoneView.as_view(), name="password_change_done",),
  # path("password_reset/", views.PasswordResetView.as_view(), name="password_reset"),
  # path("password_reset/done/", views.PasswordResetDoneView.as_view(), name="password_reset_done",),
  # path("reset/<uidb64>/<token>/", views.PasswordResetConfirmView.as_view(), name="password_reset_confirm",),
  # path("reset/done/", views.PasswordResetCompleteView.as_view(), name="password_reset_complete",),
]

urlpatterns += [
  path("", views.LoginView.as_view(), name="home"),
]

Crm/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.urls import re_path
from django.views.static import serve

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("crm.urls")),
    path("account/", include("account.urls")),
    path("ticket/", include("tickets.urls")),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += [
        re_path(
            r"^media/(?P<path>.*)$",
            serve,
            {
                "document_root": settings.MEDIA_ROOT,
            },
        ),
    ]

Crm/crm/urls.py
from django.urls import path, include
from .views import (
                      home,
                      ProjectList_stage1,
                      ProjectList_stage2,
                      ProjectList_stage3,
                      ProjectList_stage4,
                      ProjectList_stage5,
                      ProjectList_stage6,
                      ProjectList_stage7,
                      ProjectList_stage8,
                      ProjectList_stage9,
                      ProjectCreate,
                      ProjectUpdate_stage1,
                      ProjectUpdate_stage2,
                      ProjectUpdate_stage3,
                      ProjectUpdate_stage4,
                      ProjectUpdate_stage5,
                      ProjectUpdate_stage7,
                      ProjectUpdate_stage8,
                      ProjectUpdate_stage9,
                      customer_profile,
                      Support_profile,
                    )

app_name = "crm"
urlpatterns = [
  path("", home, name="home"),
  path("project/list/stage1", ProjectList_stage1.as_view(), name="ProjectList-stage1"),
  path("project/list/stage2", ProjectList_stage2.as_view(), name="ProjectList-stage2"),
  path("project/list/stage3", ProjectList_stage3.as_view(), name="ProjectList-stage3"),
  path("project/list/stage4", ProjectList_stage4.as_view(), name="ProjectList-stage4"),
  path("project/list/stage5", ProjectList_stage5.as_view(), name="ProjectList-stage5"),
  path("project/list/stage6", ProjectList_stage6.as_view(), name="ProjectList-stage6"),
  path("project/list/stage7", ProjectList_stage7.as_view(), name="ProjectList-stage7"),
  path("project/list/stage8", ProjectList_stage8.as_view(), name="ProjectList-stage8"),
  path("project/list/stage9", ProjectList_stage9.as_view(), name="ProjectList-stage9"),
  path("project/create", ProjectCreate.as_view(), name="projectCreate"),
  path("project/stage1/<int:pk>", ProjectUpdate_stage1.as_view(), name="projectCreate-stage1"),
  path("project/stage2/<int:pk>", ProjectUpdate_stage2.as_view(), name="projectCreate-stage2"),
  path("project/stage3/<int:pk>", ProjectUpdate_stage3.as_view(), name="projectCreate-stage3"),
  path("project/stage4/<int:pk>", ProjectUpdate_stage4.as_view(), name="projectCreate-stage4"),
  path("project/stage5/<int:pk>", ProjectUpdate_stage5.as_view(), name="projectCreate-stage5"),
  path("project/stage7/<int:pk>", ProjectUpdate_stage7.as_view(), name="projectCreate-stage7"),
  path("project/stage8/<int:pk>", ProjectUpdate_stage8.as_view(), name="projectCreate-stage8"),
  path("project/stage9/<int:pk>", ProjectUpdate_stage9.as_view(), name="projectCreate-stage9"),
  path("customer-profile/", customer_profile, name="customer-profile"),
  path("support-profile/", Support_profile.as_view(), name="support-profile"),
]

Crm/tickets/urls.py
from django.urls import path
from .views import Create_tickets, ticket_details, delete_message


app_name = "tickets"
urlpatterns = [
    path('create_ticket/', Create_tickets.as_view(), name='create_ticket'),
    path('ticket_details/<int:ticket_id>/', ticket_details, name='ticket_details'),
    path('delete/<int:id>/', delete_message, name='delete_message'),
]

Crm/crm/forms.py
from django import forms
from customer.models import Customer
from account.models import User


class CustomerProfileForm(forms.ModelForm):
  def __init__(self, *args, **kwargs):
    
    super(CustomerProfileForm, self).__init__(*args, **kwargs)
    
  class Meta:
      model = Customer
      fields = ["brand_name","adress","province","city"]


class SupportProfileForm(forms.ModelForm):
  def __init__(self, *args, **kwargs):
    user = kwargs.pop("user")
    
    super(SupportProfileForm, self).__init__(*args, **kwargs)
    
    self.fields["username"].help_text = None
    
    if not user.is_superuser:
      self.fields["username"].disabled = True
      self.fields["email"].disabled = True
      self.fields["is_manager"].disabled = True
      self.fields["is_customer"].disabled = True
    
  class Meta:
      model = User
      fields = ["username","email","first_name","last_name","is_manager","is_customer"]

Crm/crm/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import Http404
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.urls import reverse_lazy
from .mixins import (
                      FormValidMixin,
                      CreateFieldMixin,
                      AccessMixin,
                      UpdateFieldStage1Mixin,
                      UpdateFieldStage2Mixin,
                      UpdateFieldStage3Mixin,
                      UpdateFieldStage4Mixin,
                      UpdateFieldStage5Mixin,
                      UpdateFieldStage7Mixin,
                      UpdateFieldStage8Mixin,
                      UpdateFieldStage9Mixin,
                      Customer_ListView,
                      Genral_listView,
                      Support_ListView,
                      SupportAccessMixin
                    )
# from django.urls import reverse_lazy
from django.views.generic import (
                                    ListView, 
                                    DetailView, 
                                    CreateView, 
                                    UpdateView
                                  )
from .models import Project_procedure
from customer.models import Customer
from account.models import User
from tickets.models import Ticket, Message
from .forms import CustomerProfileForm, SupportProfileForm

# Create your views here.
# Dashboard
@login_required
def home(request):
  context = {
    "projects": Project_procedure.objects.filter(user=request.user).order_by("-created"),
    "tickets": Ticket.objects.filter(Q(customer=request.user) | Q(support=request.user))
  }
  
  return render(request, "crm/index.html", context)


# This view will show stage one item that i describe in database model in the list
class ProjectList_stage1(LoginRequiredMixin, Customer_ListView, ListView):
  template_name = "crm/project_listView_stage_1.html"


# This view will show stage two item that i describe in database model in the list
class ProjectList_stage2(LoginRequiredMixin, Customer_ListView, ListView):
  template_name = "crm/project_listView_stage_2.html"


# This view will show stage four item that i describe in database model in the list
class ProjectList_stage3(LoginRequiredMixin, Customer_ListView, ListView):
  template_name = "crm/project_listView_stage_3.html"


# This view will show stage four item that i describe in database model in the list
class ProjectList_stage4(LoginRequiredMixin, Customer_ListView, ListView):
  template_name = "crm/project_listView_stage_4.html"


# This view will show stage four item that i describe in database model in the list
class ProjectList_stage5(LoginRequiredMixin, Customer_ListView, ListView):
  template_name = "crm/project_listView_stage_5.html"


# This view will create project that's we want it from customer
class ProjectCreate(AccessMixin, CreateFieldMixin, FormValidMixin, CreateView):
  model = Project_procedure
  success_url = reverse_lazy("crm:ProjectList-stage1")
  template_name = "crm/create_project.html"


# This view will update record of table that create with model (Project_procedure) 
# the fields are title and rfp
class ProjectUpdate_stage1(AccessMixin, UpdateFieldStage1Mixin, FormValidMixin, UpdateView):
  model = Project_procedure
  success_url = reverse_lazy("crm:ProjectList-stage1")
  template_name = "crm/project_update_stage_1.html"


# This view will update record of table that create with model (Project_procedure) 
# the fields are confirm_proposal and description_reject_proposal
class ProjectUpdate_stage2(AccessMixin, UpdateFieldStage2Mixin, FormValidMixin, UpdateView):
  model = Project_procedure
  success_url = reverse_lazy("crm:ProjectList-stage2")
  template_name = "crm/project_update_stage_2.html"


# This view will update record of table that create with model (Project_procedure) 
# the fields are contract_image
class ProjectUpdate_stage3(AccessMixin, UpdateFieldStage3Mixin, FormValidMixin, UpdateView):
  model = Project_procedure
  success_url = reverse_lazy("crm:ProjectList-stage3")
  template_name = "crm/project_update_stage_3.html"


# This view will update record of table that create with model (Project_procedure) 
# the fields are payment_receipt_image
class ProjectUpdate_stage4(AccessMixin, UpdateFieldStage4Mixin, FormValidMixin, UpdateView):
  model = Project_procedure
  success_url = reverse_lazy("crm:ProjectList-stage4")
  template_name = "crm/project_update_stage_4.html"


# This view will update record of table that create with model (Project_procedure) 
# the fields are confirm_design and description_reject_design
class ProjectUpdate_stage5(AccessMixin, UpdateFieldStage5Mixin, FormValidMixin, UpdateView):
  model = Project_procedure
  success_url = reverse_lazy("crm:ProjectList-stage5")
  template_name = "crm/project_update_stage_5.html"


class ProjectList_stage6(LoginRequiredMixin, Support_ListView, ListView):
  template_name = "crm/project_listView_stage_6.html"


class ProjectList_stage7(LoginRequiredMixin, Support_ListView, ListView):
  template_name = "crm/project_listView_stage_7.html"


class ProjectList_stage8(LoginRequiredMixin, Support_ListView, ListView):
  template_name = "crm/project_listView_stage_8.html"


class ProjectList_stage9(LoginRequiredMixin, Support_ListView, ListView):
  template_name = "crm/project_listView_stage_9.html"


class ProjectUpdate_stage7(AccessMixin, UpdateFieldStage7Mixin, FormValidMixin, UpdateView):
  model = Project_procedure
  success_url = reverse_lazy("crm:ProjectList-stage7")
  template_name = "crm/project_update_stage_7.html"


class ProjectUpdate_stage8(AccessMixin, UpdateFieldStage8Mixin, FormValidMixin, UpdateView):
  model = Project_procedure
  success_url = reverse_lazy("crm:ProjectList-stage8")
  template_name = "crm/project_update_stage_8.html"


class ProjectUpdate_stage9(AccessMixin, UpdateFieldStage9Mixin, FormValidMixin, UpdateView):
  model = Project_procedure
  success_url = reverse_lazy("crm:ProjectList-stage9")
  template_name = "crm/project_update_stage_9.html"
  

class Support_profile(LoginRequiredMixin, SupportAccessMixin, UpdateView):
  model = User
  template_name = "crm/profile.html"
  form_class = SupportProfileForm
  success_url = reverse_lazy("crm:support-profile")
  
  def get_object(self):
    return User.objects.get(pk = self.request.user.pk)
  
  def get_form_kwargs(self):
    kwargs = super(Support_profile, self).get_form_kwargs()
    kwargs.update({
      "user": self.request.user
    })
    
    return kwargs


@login_required
def customer_profile(request):
    if request.user.is_customer or request.user.is_superuser:
      instance, created = Customer.objects.get_or_create(customer=request.user)

      if request.method == 'POST':
          form = CustomerProfileForm(request.POST, instance=instance)

          if form.is_valid():
              form.save()
              return redirect('/')
      else:
          form = CustomerProfileForm(instance=instance)

      context = {
          'form': form,
          'is_create': created,
      }
      return render(request, 'crm/profile.html', context)
    else:
      raise Http404("You can't access this page.")

Crm/templates/crm/base.html
{% comment %} Create file for section that will repeat again {% endcomment %}

{% load static %}
<!doctype html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang=""> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8" lang=""> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9" lang=""> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js" lang="en">
<!--<![endif]-->

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Sufee Admin - HTML5 Admin Template</title>
    <meta name="description" content="Sufee Admin - HTML5 Admin Template">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="apple-touch-icon" href="{% static  'crm/apple-icon.png' %}">
    <link rel="shortcut icon" href="{% static  'crm/favicon.ico' %}">

    <link rel="stylesheet" href="{% static  'crm/vendors/bootstrap/dist/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static  'crm/vendors/font-awesome/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static  'crm/vendors/themify-icons/css/themify-icons.css' %}">
    <link rel="stylesheet" href="{% static  'crm/vendors/flag-icon-css/css/flag-icon.min.css' %}">
    <link rel="stylesheet" href="{% static  'crm/vendors/selectFX/css/cs-skin-elastic.css' %}">
    <link rel="stylesheet" href="{% static  'crm/vendors/jqvmap/dist/jqvmap.min.css' %}">


    <link rel="stylesheet" href="{% static  'crm/assets/css/style.css' %}">
    <link rel="stylesheet" href="{% static  'crm/assets/css/rtl.css' %}">

    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,600,700,800' rel='stylesheet' type='text/css'>

</head>

<body>

  {% include "crm/sidebar.html" %}

  <div id="right-panel" class="right-panel">
    <!-- Header-->
    <header id="header" class="header">

      <div class="header-menu">

        

        <div class="col-sm-12">
            <div class="user-area float-left">
                <a href="{% url 'account:logout' %}" class="d-flex align-items-center">
                    خروج
                    <i class="fa fa-sign-out fa-rotate-180 mr-2" aria-hidden="true"></i>
                </a>
            </div>
        </div>
      </div>

    </header><!-- /header -->
    <div class="content mt-3">
      {% block main %}{% endblock %}
    </div> 
  </div>

  
  


  <script src="{% static 'crm/vendors/jquery/dist/jquery.min.js' %}"></script>
  <script src="{% static 'crm/vendors/popper.js/dist/umd/popper.min.js' %}"></script>
  <script src="{% static 'crm/vendors/bootstrap/dist/js/bootstrap.min.js' %}"></script>
  <script src="{% static 'crm/assets/js/main.js' %}"></script>


  <script src="{% static 'crm/vendors/chart.js/dist/Chart.bundle.min.js' %}"></script>
  <script src="{% static 'crm/assets/js/dashboard.js' %}"></script>
  <script src="{% static 'crm/assets/js/widgets.js' %}"></script>
  <script src="{% static 'crm/vendors/jqvmap/dist/jquery.vmap.min.js' %}"></script>
  <script src="{% static 'crm/vendors/jqvmap/examples/js/jquery.vmap.sampledata.js' %}"></script>
  <script src="{% static 'crm/vendors/jqvmap/dist/maps/jquery.vmap.world.js' %}"></script>
  <script>
      (function($) {
          "use strict";

          jQuery('#vmap').vectorMap({
              map: 'world_en',
              backgroundColor: null,
              color: '#ffffff',
              hoverOpacity: 0.7,
              selectedColor: '#1de9b6',
              enableZoom: true,
              showTooltip: true,
              values: sample_data,
              scaleColors: ['#1de9b6', '#03a9f5'],
              normalizeFunction: 'polynomial'
          });
      })(jQuery);
  </script>
  <script src="{% static 'crm/assets/js/custom.js' %}"></script>

</body>

</html>

Crm/templates/crm/index.html
{% extends "crm/base.html" %}

{% load static %}
{% load humanize %}

{% block main %}
  <div>
    <h1 class="dashboard_header">داشبورد</h1>
    {% comment %} website status {% endcomment %}
    <div class="col-lg-8 mb-4">
      <div class="card-group">
         <div class="card col-md-6 no-padding ">
            <div class="card-body">
               <div class="h1 text-muted text-right mb-4">
                  <i class="fa fa-user-plus"></i>
               </div>
               <small class="text-muted text-uppercase font-weight-bold">مشتری های جدید</small>
               <div class="h4 mb-0">
                  <span class="count">385</span>
               </div>
               <div class="progress progress-xs mt-3 mb-0 bg-flat-color-2" style="width: 40%; height: 5px;"></div>
            </div>
         </div>
         <div class="card col-md-6 no-padding ">
            <div class="card-body">
               <div class="h1 text-muted text-right mb-4">
                  <i class="fa fa-cart-plus"></i>
               </div>
               <small class="text-muted text-uppercase font-weight-bold">تعداد خدمات نرم افزاری</small>
               <div class="h4 mb-0">
                  <span class="count">1238</span>
               </div>
               <div class="progress progress-xs mt-3 mb-0 bg-flat-color-3" style="width: 40%; height: 5px;"></div>
            </div>
         </div>
         <div class="card col-md-6 no-padding ">
            <div class="card-body">
               <div class="h1 text-muted text-right mb-4">
                  <i class="fa fa-pie-chart"></i>
               </div>
               <small class="text-muted text-uppercase font-weight-bold">مشتری های راضی از ما</small>
               <div class="h4 mb-0">
                  <span class="count">93</span>%
               </div>
               <div class="progress progress-xs mt-3 mb-0 bg-flat-color-4" style="width: 40%; height: 5px;"></div>
            </div>
         </div>
         <div class="card col-md-6 no-padding ">
            <div class="card-body">
               <div class="h1 text-muted text-right mb-4">
                  <i class="fa fa-clock-o"></i>
               </div>
               <small class="text-muted text-uppercase font-weight-bold">میانگین زمان تولید نرم افزار</small>
               <div class="h4 mb-0">2 ماه</div>
               <div class="progress progress-xs mt-3 mb-0 bg-flat-color-5" style="width: 40%; height: 5px;"></div>
            </div>
         </div>
      </div>
    </div>


    {% comment %} Profile {% endcomment %}
    <div class="col-lg-4">
      <div class="card">
         <div class="card-header">
            <strong class="card-title mb-3">پروفایل</strong>
         </div>
         <div class="card-body">
            <div class="mx-auto d-block">
               <h5 class="text-sm-center mt-2 mb-1">{{ user.username }}</h5>
               <div class="location text-sm-center"><i class="fa fa-email"></i>{{ user.email }}</div>
            </div>
            <hr>
            <div class="card-text text-sm-center">
               <a href="#"><i class="fa fa-facebook pr-1"></i></a>
               <a href="#"><i class="fa fa-twitter pr-1"></i></a>
               <a href="#"><i class="fa fa-linkedin pr-1"></i></a>
               <a href="#"><i class="fa fa-pinterest pr-1"></i></a>
            </div>
         </div>
      </div>
   </div>


   {% comment %} The last projects {% endcomment %}
   <div class="col-lg-5">
    <div class="card">
       <div class="card-header d-flex justify-content-between">
          <strong class="card-title">چندین پروژه آخر</strong>
            <a class="d-flex align-items-center" href="{% url 'crm:projectCreate' %}">
              ایجاد پروژه جدید
              <span class="plus_icon mr-2">
                &#x2b;
              </span>
            </a>
       </div>
       <div class="card-body">
        <table class="table">
          <thead class="bg-dark text-white">
            <tr>
              <tr role="row">
                <th 
                  class="sorting_asc text-center" 
                  tabindex="0" 
                  aria-controls="bootstrap-data-table-export" 
                  rowspan="1" 
                  colspan="1" 
                  aria-sort="ascending" aria-label="Name: activate to sort column descending" 
                  style="width: auto;">
                  عنوان پروژه
                </th>
                <th 
                  class="sorting_asc text-center" 
                  tabindex="0" 
                  aria-controls="bootstrap-data-table-export" 
                  rowspan="1" 
                  colspan="1" 
                  aria-sort="ascending" aria-label="Name: activate to sort column descending" 
                  style="width: auto;">
                  زمان ثبت اولیه پروژه
                </th>
            </tr>
          </thead>
          <tbody>
            {% for project in projects %}
             {% if forloop.counter <= 4 %}
               
                 <tr>
                   <td>
                     {{ project.project_title }}
                   </td>
                   <td>{{ project.jcreate|naturaltime  }}</td>
                 </tr>
               {% endif %}
            {% endfor %}
          </tbody>
        </table>
       </div>
    </div>
 </div>

 {% comment %} send messages for ticket {% endcomment %}
 <div class="col-lg-7">
  <div class="card">
     <div class="card-header d-flex justify-content-between">
        <strong class="card-title">تیکت های ارسال شده</strong>
     </div>
     <div class="card-body">
      <table class="table">
        <thead class="bg-dark text-white">
          <tr>
            <tr role="row">
              <th 
                class="sorting_asc text-center" 
                tabindex="0" 
                aria-controls="bootstrap-data-table-export" 
                rowspan="1" 
                colspan="1" 
                aria-sort="ascending" aria-label="Name: activate to sort column descending" 
                style="width: auto;">
                 مشتری
              </th>
              <th 
                class="sorting_asc text-center" 
                tabindex="0" 
                aria-controls="bootstrap-data-table-export" 
                rowspan="1" 
                colspan="1" 
                aria-sort="ascending" aria-label="Name: activate to sort column descending" 
                style="width: auto;">
                پشتیبانی
              </th>
              <th 
                class="sorting_asc text-center" 
                tabindex="0" 
                aria-controls="bootstrap-data-table-export" 
                rowspan="1" 
                colspan="1" 
                aria-sort="ascending" aria-label="Name: activate to sort column descending" 
                style="width: auto;">
                موضوع
              </th>
              <th 
                class="sorting_asc text-center" 
                tabindex="0" 
                aria-controls="bootstrap-data-table-export" 
                rowspan="1" 
                colspan="1" 
                aria-sort="ascending" aria-label="Name: activate to sort column descending" 
                style="width: auto;">
                زمان ارسال
              </th>
              <th 
                class="sorting_asc text-center" 
                tabindex="0" 
                aria-controls="bootstrap-data-table-export" 
                rowspan="1" 
                colspan="1" 
                aria-sort="ascending" aria-label="Name: activate to sort column descending" 
                style="width: auto;">
                ارسال پیام
              </th>
          </tr>
        </thead>
        <tbody>
          {% for ticket in tickets %}
            <tr>
              <td>
                {{ ticket.customer }}
              </td>
              <td>
                {% if ticket.support %}
                  {{ ticket.support }}
                {% else %}
                  ....
                {% endif %}
              </td>
              <td>
                {{ ticket.subject }}
              </td>
              <td>
                {{ ticket.ticket_jcreate }}
              </td>
              <td>
                <a href="{% url 'tickets:ticket_details' ticket_id=ticket.id %}">
                  <span class="plus_icon mr-2">
                    &#x2b;
                  </span>
                </a>
              </td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
     </div>
  </div>
</div>

</div>
{% endblock %}

Crm/templates/crm/sidebar.html
<!-- Left Panel -->
{% load static %}
<aside id="left-panel" class="left-panel">
    <nav class="navbar navbar-expand-lg navbar-default">

        <div class="navbar-header">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#main-menu" aria-controls="main-menu" aria-expanded="false" aria-label="Toggle navigation">
                <i class="fa fa-bars"></i>
            </button>
            <a href="#" class="side-bar-user-name d-block">
                {% if user.get_full_name %}
                  {{ user.get_full_name }}
                {% else %}
                  {{ user.username }}
                {% endif %}
            </a>
        </div>

        <div id="main-menu" class="main-menu collapse navbar-collapse">
            <ul class="nav navbar-nav">
                {% if user.is_customer %}
                    <li class="active">
                        <a href="{% url 'crm:home' %}"> <i class="menu-icon fa fa-dashboard"></i>داشبورد</a>
                    </li>
                    <li class="menu-item-has-children dropdown active">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="menu-icon fa fa-laptop"></i>
                            ثبت سفارش
                        </a>
                        <ul class="sub-menu children dropdown-menu">
                            <li class="active">
                                <a href="{% url 'crm:ProjectList-stage1' %}">
                                    <i class="menu-icon fa fa-plus-square-o"></i>
                                    ۱. تعریف پروژه 
                                </a>
                            </li>
                            <hr />
                            <li class="active">
                                <a href="{% url 'crm:ProjectList-stage2' %}">
                                    <i class="menu-icon fa fa-plus-square-o"></i>
                                    ۲. دریافت و تایید پرپوزال 
                                </a>
                            </li>
                            <hr />
                            <li class="active">
                                <a href="{% url 'crm:ProjectList-stage3' %}">
                                    <i class="menu-icon fa fa-plus-square-o"></i>
                                    ۳. ارسال قرار داد و دریافت تاییدیه
                                </a>
                            </li>
                            <hr />
                            <li class="active">
                                <a href="{% url 'crm:ProjectList-stage4' %}">
                                    <i class="menu-icon fa fa-plus-square-o"></i>
                                    ۴. ارسال رسید پرداخت و دریافت تاییدیه
                                </a>
                            </li>
                            <hr />
                            <li class="active">
                                <a href="{% url 'crm:ProjectList-stage5' %}">
                                    <i class="menu-icon fa fa-plus-square-o"></i>
                                    ۵. دریافت و تایید طراحی
                                </a>
                            </li>
                            <hr />
                        </ul>
                    </li>
                    <li class="active">
                        <a href="{% url 'crm:customer-profile' %}"> <i class="menu-icon fa fa-user"></i>پروفایل</a>
                    </li>
                    <li class="active">
                        <a href="{% url 'tickets:create_ticket' %}"> <i class="menu-icon fa fa-tags"></i>ارسال تیکت</a>
                    </li>
                {% endif %}

                {% if user.is_manager %}
                    <li class="active">
                        <a href="{% url 'crm:home' %}"> <i class="menu-icon fa fa-dashboard"></i>داشبورد</a>
                    </li>
                    <li class="menu-item-has-children dropdown active">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="menu-icon fa fa-laptop"></i>
                            ثبت سفارش
                        </a>
                        <ul class="sub-menu children dropdown-menu">
                            <li class="active">
                                <a href="{% url 'crm:ProjectList-stage6' %}">
                                    <i class="menu-icon fa fa-plus-square-o"></i>
                                    ۱. دریافت RFP
                                </a>
                            </li>
                            <hr />
                            <li class="active">
                                <a href="{% url 'crm:ProjectList-stage7' %}">
                                    <i class="menu-icon fa fa-plus-square-o"></i>
                                    ۲. ارسال پرپوزال
                                </a>
                            </li>
                            <hr />
                            <li class="active">
                                <a href="{% url 'crm:ProjectList-stage8' %}">
                                    <i class="menu-icon fa fa-plus-square-o"></i>
                                    ۳. ارسال قرارداد و پیش فاکتور
                                </a>
                            </li>
                            <hr />
                            <li class="active">
                                <a href="{% url 'crm:ProjectList-stage9' %}">
                                    <i class="menu-icon fa fa-plus-square-o"></i>
                                    ۴. دریافت قرارداد و رسید پرداخت
                                </a>
                            </li>
                            <hr />
                        </ul>
                    </li>

                    <li class="active">
                        <a href="{% url 'crm:support-profile' %}"> <i class="menu-icon fa fa-user"></i>پروفایل</a>
                    </li>
                {% endif %}
            </ul>
        </div><!-- /.navbar-collapse -->
    </nav>
</aside><!-- /#left-panel -->

<!-- Left Panel -->