Crm/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.urls import re_path
from django.views.static import serve

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("crm.urls")),
    path("account/", include("account.urls")),
    path("ticket/", include("tickets.urls")),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += [
        re_path(
            r"^media/(?P<path>.*)$",
            serve,
            {
                "document_root": settings.MEDIA_ROOT,
            },
        ),
    ]

Crm/crm/urls.py
from django.urls import path, include
from .views import (
                      home,
                      ProjectList_stage1,
                      ProjectList_stage2,
                      ProjectList_stage3,
                      ProjectList_stage4,
                      ProjectList_stage5,
                      ProjectList_stage6,
                      ProjectList_stage7,
                      ProjectList_stage8,
                      ProjectList_stage9,
                      ProjectCreate,
                      ProjectUpdate_stage1,
                      ProjectUpdate_stage2,
                      ProjectUpdate_stage3,
                      ProjectUpdate_stage4,
                      ProjectUpdate_stage5,
                      ProjectUpdate_stage7,
                      ProjectUpdate_stage8,
                      ProjectUpdate_stage9,
                      customer_profile,
                      Support_profile,
                    )

app_name = "crm"
urlpatterns = [
  path("", home, name="home"),
  path("project/list/stage1", ProjectList_stage1.as_view(), name="ProjectList-stage1"),
  path("project/list/stage2", ProjectList_stage2.as_view(), name="ProjectList-stage2"),
  path("project/list/stage3", ProjectList_stage3.as_view(), name="ProjectList-stage3"),
  path("project/list/stage4", ProjectList_stage4.as_view(), name="ProjectList-stage4"),
  path("project/list/stage5", ProjectList_stage5.as_view(), name="ProjectList-stage5"),
  path("project/list/stage6", ProjectList_stage6.as_view(), name="ProjectList-stage6"),
  path("project/list/stage7", ProjectList_stage7.as_view(), name="ProjectList-stage7"),
  path("project/list/stage8", ProjectList_stage8.as_view(), name="ProjectList-stage8"),
  path("project/list/stage9", ProjectList_stage9.as_view(), name="ProjectList-stage9"),
  path("project/create", ProjectCreate.as_view(), name="projectCreate"),
  path("project/stage1/<int:pk>", ProjectUpdate_stage1.as_view(), name="projectCreate-stage1"),
  path("project/stage2/<int:pk>", ProjectUpdate_stage2.as_view(), name="projectCreate-stage2"),
  path("project/stage3/<int:pk>", ProjectUpdate_stage3.as_view(), name="projectCreate-stage3"),
  path("project/stage4/<int:pk>", ProjectUpdate_stage4.as_view(), name="projectCreate-stage4"),
  path("project/stage5/<int:pk>", ProjectUpdate_stage5.as_view(), name="projectCreate-stage5"),
  path("project/stage7/<int:pk>", ProjectUpdate_stage7.as_view(), name="projectCreate-stage7"),
  path("project/stage8/<int:pk>", ProjectUpdate_stage8.as_view(), name="projectCreate-stage8"),
  path("project/stage9/<int:pk>", ProjectUpdate_stage9.as_view(), name="projectCreate-stage9"),
  path("customer-profile/", customer_profile, name="customer-profile"),
  path("support-profile/", Support_profile.as_view(), name="support-profile"),
]

Crm/tickets/urls.py
from django.urls import path
from .views import Create_tickets, ticket_details, delete_message


app_name = "tickets"
urlpatterns = [
    path('create_ticket/', Create_tickets.as_view(), name='create_ticket'),
    path('ticket_details/<int:ticket_id>/', ticket_details, name='ticket_details'),
    path('delete/<int:id>/', delete_message, name='delete_message'),
]

Crm/tickets/models.py
from django.db import models
from account.models import User
from extensions.utils import jalali_converter


class Ticket(models.Model):
  customer = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="مشتری")
  support = models.ForeignKey(User, on_delete=models.CASCADE, related_name='assigned_tickets', blank=True, null=True, verbose_name="ساپورت")
  subject = models.CharField(max_length=200, verbose_name="موضوع")
  description = models.TextField(verbose_name="توضیحات")
  created_at = models.DateTimeField(auto_now_add=True, verbose_name="زمان ارسال")
  updated_at = models.DateTimeField(auto_now=True, verbose_name="زمان ویرایش")
  
  class Meta:
    verbose_name = "تیکت"
    verbose_name_plural = "تیکت ها"
    ordering = ["-created_at"]
    
    
  def ticket_jcreate(self):
    return jalali_converter(self.created_at)
  
  ticket_jcreate.short_description = "زمان ثبت ارسال پیام"


class Message(models.Model):
  ticket = models.ForeignKey(Ticket, on_delete=models.CASCADE, related_name="messages", verbose_name="تیکت")
  sender = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="ارسال کننده")
  content = models.TextField(verbose_name="محتوا")
  created_at = models.DateTimeField(auto_now_add=True, verbose_name="زمان ارسال")
  
  class Meta:
    verbose_name = "پیام"
    verbose_name_plural = "پیام ها"
    ordering = ["-created_at"]
  
  def message_jcreate(self):
    return jalali_converter(self.created_at)
  
  message_jcreate.short_description = "زمان ثبت ارسال پیام"

Crm/tickets/forms.py
from django import forms
from .models import Ticket, Message



class TicketForm(forms.ModelForm):
    class Meta:
        model = Ticket
        fields = ['subject', 'description']


class MessageForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = ['content']

Crm/tickets/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Ticket, Message
from .forms import MessageForm
from .mixins import CreateFieldMixin, FormValidMixin
from django.urls import reverse_lazy
from django.views.generic import CreateView
from django.contrib import messages


# Create your views here.
class Create_tickets(LoginRequiredMixin, CreateFieldMixin, FormValidMixin, CreateView):
  model = Ticket
  success_url = reverse_lazy("crm:home")
  template_name = "tickets/create_ticket.html"
  


@login_required
def ticket_details(request, ticket_id):
  ticket = get_object_or_404(Ticket, id=ticket_id)
  
  if request.method == "POST":
    form = MessageForm(request.POST)
    if form.is_valid():
      message = form.save(commit=False)
      message.ticket = ticket
      message.sender = request.user
      message.save()
      return redirect('tickets:ticket_details', ticket_id=ticket_id)
  else:
    form = MessageForm()
  
  return render(request, "tickets/ticket_details.html", {"ticket": ticket, "form": form})


def delete_message(request, id):
    message = get_object_or_404(Message, pk=id)
    context = {'message': message}    
    
    if request.method == 'GET':
        return render(request, 'tickets/message_confirm_delete.html',context)
    elif request.method == 'POST':
        message.delete()
        messages.success(request,  'The post has been deleted successfully.')
        return redirect('tickets:ticket_details', ticket_id=message.ticket.id)

Crm/templates/tickets/create_ticket.html
{% extends "crm/base.html" %}

{% load crispy_forms_tags %}

{% load static %}

{% block main %}
<div class="col-md-12 ticket-fonts">
  <!-- general form elements -->
  <div class="card card-primary">
    <div class="card-header">
      <h3 class="card-title mb-0 text-center"></h3>
    </div>
    <div class="card-body card-body-scroll">
      <form method="post" enctype="multipart/form-data">
        {% csrf_token %}

        <div class="row">
          <div class="col-12">
            {{ form.subject|as_crispy_field }}
          </div>

          <div class="col-12">
            {{ form.description|as_crispy_field }}
          </div>
          <div class="col-6 d-flex justify-content-end align-items-center">
            <button class="btn btn-success">ارسال</button>
          </div>
    </div>
</div>
{% endblock %}

Crm/templates/tickets/message_confirm_delete.html
{% extends "crm/base.html" %}

{% load crispy_forms_tags %}

{% load static %}

{% block main %}
<h2>Delete Post</h2>

<form method="POST">
  {% csrf_token %}
  <p>آیا شما از حذف این متن "{{message.content}}" مطمئن هستید؟</p>
  <div>
    <button type="submit" class="btn btn-danger">بله</button>
    <a href="{% url 'tickets:ticket_details' ticket_id=message.ticket.id %}" class="btn btn-success">لغو حذف</a>
  </div>
</form>

{% endblock %}

Crm/templates/tickets/ticket_details.html
{% extends "crm/base.html" %}

{% load crispy_forms_tags %}

{% load static %}

{% block main %}

<div class="col-md-12 ticket-fonts">
  <!-- general form elements -->
  <div class="card card-primary">
    <div class="card-header">
      <h3 class="card-title mb-0">جزئیات تیکت</h3>
    </div>
    <div class="card-body card-body-scroll">
      <p><b>موضوع: </b>{{ ticket.subject }}</p>
      <p><b>توضیحات:</b> {{ ticket.description }}</p>
      <section style="background-color: #eee;">
        <div class="container py-5">
      
          <div class="">
      
            <div>
              <ul class="list-unstyled col-12">
                {% for message in ticket.messages.all %}
                  {% if user.username == message.sender.username %}
                    <li class="d-flex justify-content-between mb-4">
                      <div class="card w-100">
                        <div class="card-header d-flex justify-content-between p-3 message-card-header-self">
                          <p class="fw-bold mb-0 text-dark">شما</p>
                          <p class="text-dark small mb-0"><i class="far fa-clock"></i> {{ message.message_jcreate }}</p>
                        </div>
                        <div class="card-body">
                          <p class="mb-0">
                            {{ message.content }}
                          </p>
                          <a href="{% url 'tickets:delete_message' message.id%}" class="btn btn-danger float-left">حذف</a>
                        </div>
                      </div>
                    </li>
                  {% else %}
                    <li class="d-flex justify-content-start mb-4">
                      <div class="card w-100">
                        {% if user.is_customer %}
                          <div class="card-header d-flex justify-content-between p-3 message-card-header-others">
                            <p class="fw-bold mb-0 text-white">پشتیبانی</p>
                            <p class="text-white small mb-0"><i class="far fa-clock"></i> {{ message.message_jcreate }}</p>
                          </div>
                        {% else %}
                          <div class="card-header d-flex justify-content-between p-3 message-card-header-others">
                            <p class="fw-bold mb-0 text-white">مشتری</p>
                            <p class="text-white small mb-0"><i class="far fa-clock"></i> {{ message.message_jcreate }}</p>
                          </div>
                        {% endif %}
                        <div class="card-body">
                          <p class="mb-0">
                            {{ message.content }}
                          </p>
                        </div>
                        </div>
                        {% endif %}
                    </li>
                {% endfor %}
                
                
                <li class="bg-white mb-3">
                  <div class="form-outline">
                    <form method="post">
                      {% csrf_token %}
              
                      <div class="row">
                        <div class="col-12">
                          {{ form.content|as_crispy_field }}
                        </div>
              
                        <div class="col-6 d-flex justify-content-end align-items-center">
                          <button class="btn btn-success btn-rounded float-end">ارسال</button>
                        </div>
                    </form>
                  </div>
                </li>
              </ul>
      
            </div>
      
          </div>
      
        </div>
      </section> 
      
    </div>
    
</div>
{% endblock %}